name: Deploy to GitHub Pages

on:
  push:
    branches: [ buntest ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install Dependencies
        run: |
          if [ -f "package.json" ]; then
            npm install
          fi

      - name: Build
        run: |
          if [ -f "build.sh" ]; then
            chmod +x build.sh
            ./build.sh
          else
            mkdir -p build
            cp -r index.html about.html work.html contact.html reel.html build/
            cp -r assets build/
            cp -r css build/
            cp -r js build/
          fi

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          branch: gh-pages 